insert into public.budget_insights (
  user_id,
  insight_month,
  type,
  severity,
  title,
  body,
  category,
  category_label,
  budget_bucket,
  current_amount,
  suggested_limit,
  expected_saving,
  action_label,
  action_payload,
  status,
  source
) values (
  'default',
  '2026-07',
  'saving_opportunity',
  'warning',
  '외식·배달 한도를 낮출 수 있어요',
  '최근 외식·배달 지출이 32,000원입니다. 이번 주 한도를 20,000원으로 낮추면 약 12,000원을 아낄 수 있어요.',
  'food_delivery',
  '외식·배달',
  'want',
  32000,
  20000,
  12000,
  '한도 적용하기',
  '{"budgetCategory":"food_delivery","limit":20000}',
  'active',
  'dummy_seed'
);
